on: push
name: ğŸš€ Deploy website on push
jobs:
  web-deploy-client:
    name: ğŸ‰ Deploy client
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Get latest code
      uses: actions/checkout@v3
    
    - name: ğŸ“‚ Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.ftp_server }}
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        local-dir: ./client/dist/
        server-dir: ./bookstack.joshkaye.ca/
  # web-deploy-api:
  #   name: ğŸ‰ Deploy api
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: ğŸšš Get latest code
  #     uses: actions/checkout@v3
    
  #   - name: ğŸ“‚ Sync files
  #     uses: SamKirkland/FTP-Deploy-Action@4.3.3
  #     with:
  #       server: ${{ secrets.ftp_server }}
  #       username: ${{ secrets.ftp_username }}
  #       password: ${{ secrets.ftp_password }}
  #       local-dir: ./api/
  #       server-dir: ./bookstackapi.joshkaye.ca/
